title: Martin Bernardo Meza
logo: /assets/img/logo.png
description:
    Tesiste de la carrera Ingeniería de Sonido
    <br><br>
    Inteligencia Artificial y Machine Learning
    <br><br>
    Python Developer
    <br><br>
    <a href="https://www.linkedin.com/in/martin-bernardo-meza/">Perfil de Linkedin</a>
    <a href="https://github.com/martinBmeza">Perfil de GitHub</a>

show_downloads: true
google_analytics: G-S0SP1Y5PQB
theme: jekyll-theme-minimal
