title: Martin Bernardo Meza
logo: /assets/img/logo.png
description:
    <p align="center">
    <a href="pdf/resume.pdf">Curriculum</a> |
    <a href="https://www.linkedin.com/in/martin-bernardo-meza/">LinkedIn</a> |
    <a href="https://github.com/martinBmeza">GitHub</a> 
    </p>

    <p align="justify">
    I'm a Sound Engineering advanced student, and I have finished my final thesis work named "Speech Dereverberation using Deep Learning algorithms". Furthermore, I currently have a position as teaching fellow in Signal and Systems asignature at Universidad Nacional Tres de Febrero, where I mainly work with audio signal processes and Python programming.

    <br><br>
    I'm interested in the application of deep learning techniques to audio signal processing and analysis. More precisely, I especially like to work in applications related to speech signals.    </p>

show_downloads: false
google_analytics: G-M58VBTTBEQ
theme: jekyll-theme-minimal
